name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4   # On reste dans TP4

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Lint
      - name: Run flake8
        run: python -m flake8 app tests

      # 5️⃣ Tests unitaires avec coverage
      - name: Run tests with coverage
        run: |
          PYTHONPATH=${{ github.workspace }}/TP4 python -m pytest tests --cov=app --cov-fail-under=80
