name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r TP4/requirements.txt

      # 4️⃣ Vérifier le style
      - name: Run flake8
        run: python -m flake8 TP4/app TP4/tests

      # 5️⃣ Lancer les tests unitaires avec couverture
      - name: Run tests with coverage
        run: python -m pytest TP4/tests --cov=TP4/app --cov-fail-under=80
        env:
          PYTHONPATH: ${{ github.workspace }}/TP4
