name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com  # optionnel
    steps:
      - name: Déploiement simulé
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          echo "Déploiement de l’image ghcr.io/${{ github.repository }}:latest sur production..."
          echo "Utilisation du secret : $APP_SECRET"
