name: Docker Build & Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construction et push de l'image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
