name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Permet de déclencher manuellement

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4  # Toutes les commandes se font dans TP4

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Mettre pip à jour
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Installer les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. Linter le code
      - name: Run flake8 lint
        run: python -m flake8 app tests

      # 6. Exécuter les tests avec couverture
      - name: Run tests with coverage
        run: python -m pytest --cov=app --cov-fail-under=80

      # 7. Build package Python
      - name: Build Python package
        run: |
          python -m pip install --upgrade build
          python -m build

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test   # Ne build Docker que si les tests passent
    defaults:
      run:
        working-directory: TP4

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository }}:v1.0.0
          docker build -t $IMAGE_TAG .

      # 4. Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_TAG
