name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Permet de déclencher manuellement

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Mettre pip à jour
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Installer les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. Linter le code
      - name: Run flake8 lint
        run: python -m flake8 app tests

      # 6. Exécuter les tests avec couverture
      - name: Run tests with coverage
        run: python -m pytest --cov=app --cov-fail-under=80

  build-package:
    runs-on: ubuntu-latest
    needs: build-test
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Build Python package
        run: python -m build --sdist --wheel

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (local only)
        run: |
          IMAGE_TAG=mon-utilitaire:latest
          docker build -t $IMAGE_TAG .
