name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4   # Toutes les commandes sont dans TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run lint
        run: python -m flake8 app tests

      - name: Run tests with coverage
        run: python -m pytest --cov=app --cov-fail-under=80

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=synthia12/ci-cd_synthia:latest
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME synthia12/ci-cd_synthia:${GITHUB_SHA::8}

      - name: Push Docker image
        run: |
          docker push synthia12/ci-cd_synthia:latest
          docker push synthia12/ci-cd_synthia:${GITHUB_SHA::8}
