name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Permet de déclencher manuellement

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8 lint
        run: python -m flake8 app tests

      - name: Run tests with coverage
        run: python -m pytest --cov=app --cov-fail-under=80

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_TAG=mon-utilitaire:latest
          docker build -t $IMAGE_TAG .

      - name: Save Docker image to tar
        run: |
          docker save mon-utilitaire:latest -o mon-utilitaire.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: mon-utilitaire-image
          path: mon-utilitaire.tar
