name: CI/CD

on:
  push:
    tags:
      - 'v*'   # Se déclenche quand tu pushes un tag (ex: v1.0.0)
  workflow_dispatch:

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --maxfail=1 --disable-warnings -q

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to maalsi-bnp
        run: |
          IMAGE_NAME=ghcr.io/maalsi-bnp/ci-cd_synthia:${GITHUB_REF_NAME}
          echo "Building image $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          echo "Pushing image $IMAGE_NAME"
          docker push $IMAGE_NAME
