name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Permet un déclenchement manuel

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. Lint the code
      - name: Run flake8 lint
        run: python -m flake8 app tests

      # 6. Run tests with coverage
      - name: Run tests with coverage
        run: python -m pytest --cov=app --cov-fail-under=80

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test  # Ne build Docker que si les tests passent
    defaults:
      run:
        working-directory: TP4

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository }}:v1.0.0
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
