name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # permet déclenchement manuel

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4  # Toutes les commandes se font dans TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8 lint
        run: python -m flake8 app tests

      - name: Run tests with coverage
        run: python -m pytest --cov=app --cov-fail-under=80

  build-package:
    runs-on: ubuntu-latest
    needs: build-test
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build Python package
        run: python -m build --sdist --wheel

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Docker is available
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Skipping Docker build."
            exit 0
          fi

      - name: Build Docker image
        run: |
          IMAGE_TAG=tp4-app:latest
          docker build -t $IMAGE_TAG .
