name: CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'   # Déclenche le workflow sur les tags Git pour Docker
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4   # Se place dans TP4 pour toutes les commandes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run lint
        run: python -m flake8 app tests

      - name: Run tests with coverage
        run: python -m pytest --cov=app --cov-fail-under=80

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-test   # attend que le job build-test soit terminé
    if: startsWith(github.ref, 'refs/tags/')  # ne build que sur tag Git
    defaults:
      run:
        working-directory: TP4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker build -t synthiaaaa/word-utils-app:$TAG .
          docker tag synthiaaaa/word-utils-app:$TAG synthiaaaa/word-utils-app:latest

      - name: Push Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker push synthiaaaa/word-utils-app:$TAG
          docker push synthiaaaa/word-utils-app:latest
